---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: tos
description: Fedora Kionite with my personal tweaks and modifications.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks
      - plasma-welcome-fedora
      - plasma-welcome
      - plasma-discover
      - plasma-pass
      - krfb
      - krfb-libs
      - ublue-os-update-services

  - type: akmods
    install:
      - wl

  - type: default-flatpaks
    system:
      install:
        - com.brave.Browser
        - dev.vencord.Vesktop
        - com.lunarclient.LunarClient
      remove:
        - org.mozilla.Thunderbird
        - io.github.flattool.Warehouse

  - type: signing
